import { Engine, THREE, studioEnvironment } from '../../src/core/engine.js';
import { buildMovement } from './movement.js';
import { makeStudio } from './studio.js';
import { irisUniforms } from './finish.js';
const q = new URLSearchParams(location.search);
const eng = new Engine({ canvas: document.getElementById('c'), fov: +(q.get('fov') ?? 30), near: 0.02, far: 80, background: 0xf3efe7,
  post: { tone: 'neutral', bloom: q.has('nobloom') ? false : { intensity: 0.4, luminanceThreshold: 1.3, luminanceSmoothing: 0.3 }, ao: q.has('noao') ? false : { aoRadius: 0.12, intensity: 2, distanceFalloff: 1 }, vignette: false, noise: 0.02 } });
const { scene, camera, renderer } = eng;
renderer.setClearColor(new THREE.Color(1.114, 1.073, 0.995));
const studio = makeStudio(renderer, scene, { front: +(q.get('front') ?? 1.4), dome: +(q.get('dome') ?? 1) });
const u = irisUniforms(); u.uIris.value = 1;
const t0 = performance.now();
const mv = await buildMovement({ u });
document.getElementById('i').textContent = `build ${Math.round(performance.now() - t0)}ms`;
let tris = 0; mv.root.traverse(o => { if (o.isMesh && o.geometry.index) tris += o.geometry.index.count / 3; });
document.getElementById('i').textContent += ` · ${Math.round(tris / 1000)}k tris`;
const rig = new THREE.Group(); rig.add(mv.root); scene.add(rig);
rig.rotation.x = +(q.get('rx') ?? 0) * Math.PI / 180;
rig.rotation.y = +(q.get('ry') ?? 0) * Math.PI / 180;
rig.rotation.z = +(q.get('rz') ?? 0) * Math.PI / 180;
mv.setExplode(+(q.get('e') ?? 0));
mv.st.w = +(q.get('w') ?? 0.34);
const d = +(q.get('d') ?? 5), az = +(q.get('az') ?? 0) * Math.PI / 180, el = +(q.get('el') ?? 0) * Math.PI / 180;
const tx = +(q.get('tx') ?? 0), ty = +(q.get('ty') ?? 0), tz = +(q.get('tz') ?? 0);
camera.position.set(tx + d * Math.sin(az) * Math.cos(el), ty + d * Math.sin(el), tz + d * Math.cos(az) * Math.cos(el));
camera.lookAt(tx, ty, tz);
eng.onTick(dt => mv.update(dt, { timeScale: +(q.get('ts') ?? 1) }));
renderer.compile(scene, camera);
eng.start(); setTimeout(() => { window.__ready = true; }, 600);
