// The collection, in gallery order. Used by the index and by the cross-page navigator.
export const WORLDS = [
  { slug: 'reliquary', name: 'Reliquary', line: 'A museum you can only see by lantern light', lineTr: 'Yalnızca fener ışığında görebileceğin bir müze', hue: '#c9a36a' },
  { slug: 'abyssal', name: 'Abyssal', line: 'Descend eleven thousand metres', lineTr: 'On bir bin metre aşağı in', hue: '#3fd6c9' },
  { slug: 'ember', name: 'Hammer & Ember', line: 'Heat the blade. Strike the steel.', lineTr: 'Isıt bıçağı. Vur çeliğe.', hue: '#ff6a1f' },
  { slug: 'terrarium', name: 'Bell & Moss', line: 'Wipe the glass. Meet the world inside.', lineTr: 'Camı sil. İçindeki dünyayla tanış.', hue: '#8fb57a' },
  { slug: 'koi', name: 'Still Water', line: 'Touch the pond', lineTr: 'Göle dokun', hue: '#e0503a' },
  { slug: 'florae', name: 'Florae', line: 'Two hundred thousand petals, one gesture', lineTr: 'İki yüz bin taç yaprağı, tek bir dokunuş', hue: '#d6456b' },
  { slug: 'velocity', name: 'Velocity Lab', line: 'See through the shoe', lineTr: 'Ayakkabının içinden bak', hue: '#ff8a1f' },
  { slug: 'hangar', name: 'Hangar Nine', line: 'Power up a forty-ton machine', lineTr: 'Kırk tonluk bir makineyi çalıştır', hue: '#ffb000' },
  { slug: 'sucre', name: 'Maison Sucre', line: 'A patisserie with gravity', lineTr: 'Yerçekimi olan bir pastane', hue: '#f29bb2' },
  { slug: 'monolith', name: 'Monolith', line: 'Drag the sun across a house', lineTr: 'Güneşi bir evin üzerinde sürükle', hue: '#d9c7a8' },
  { slug: 'lowfreq', name: 'Low Frequency', line: 'Put your hand on the record', lineTr: 'Elini plağın üzerine koy', hue: '#a78bfa' },
  { slug: 'gambit', name: 'Gambit', line: 'The Immortal Game, replayed in marble', lineTr: 'Ölümsüz Oyun, mermerle yeniden oynanıyor', hue: '#e9e4da' },
  { slug: 'atlas', name: 'Atlas of Drifting Isles', line: 'Travel between floating islands', lineTr: 'Yüzen adalar arasında yolculuk et', hue: '#7cc4ff' },
  { slug: 'lithos', name: 'Lithos', line: 'Crack the stone open', lineTr: 'Taşı çatlatıp aç', hue: '#9d6bff' },
  { slug: 'artemis', name: 'Artemis', line: 'Scroll to walk on the Moon', lineTr: 'Ay’da yürümek için kaydır', hue: '#dcdcdc' },
  { slug: 'keeper', name: 'The Keeper', line: 'Hold the light against the storm', lineTr: 'Işığı fırtınaya karşı yüksekte tut', hue: '#ffd27a' },
  { slug: 'koen', name: 'Kōen', line: 'One tree, four seasons', lineTr: 'Tek ağaç, dört mevsim', hue: '#d2553b' },
  { slug: 'nocturne', name: 'Nocturne', line: 'A fragrance you can pour', lineTr: 'Dökebileceğin bir koku', hue: '#d8b56a' },
  { slug: 'racer', name: 'Nightshift Motor Co.', line: 'Rev a café racer in the rain', lineTr: 'Yağmurda bir café racer’ı gazla', hue: '#ff3b5c' },
  { slug: 'horologie', name: 'Aurel Horologie', line: 'Take a movement apart', lineTr: 'Bir mekanizmayı parça parça sök', hue: '#c89b6d' },
];
